# Generated by Django 4.2.10 on 2025-03-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distrito', models.CharField(max_length=100)),
                ('metros_cuadrados', models.FloatField()),
                ('habitaciones', models.IntegerField()),
                ('precio', models.FloatField()),
                ('antiguedad', models.IntegerField()),
                ('estado', models.CharField(choices=[('Buen estado', 'Buen estado'), ('Reformado', 'Reformado'), ('A reformar', 'A reformar')], max_length=20)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
    ]
